
CXX		= $(LARLITE_CXX)
LD              = $(LARLITE_CXX)
LDFLAGS         += -Wl,-rpath,$(LARLITE_BASEDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 $(LARLITE_CXXSTDFLAG) -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = $(LARLITE_CXX)
SOFLAGS         = -g -fPIC -shared
