
CXX		= $(LARLITE_CXX)
LD              = g++
LDFLAGS         += -Wl,-rpath,$(LARLITE_BASEDIR)/lib
FFLAGS          += -Wall
FLDFLAGS        += -lstdc++ -shared 
CXXFLAGS        += -g -O3 $(LARLITE_CXXSTDFLAG) -W -Wall -Wno-deprecated -fPIC -D_CORE_$(shell uname -s)_
SOMAKER         = g++
SOFLAGS         = -g -fPIC -shared
