/**
 * \file AlgoCCSignalE.h
 *
 * \ingroup SPAlgo
 * 
 * \brief This SPAlgo takes in electrons and returns electrons that are likely
 generated by a neutrino in a CC interaction.
 * It checks things like:
 *    - The electron is not at the end of a track (IE Michels)
 *    - The electron is not radiated off of another electron shower
 *    - The electron is not radiated off of another track
 *    - etc.
 *
 * @author davidkaleko
 */

/** \addtogroup SPAlgo

    @{*/

#ifndef ERTOOL_ALGOCCSIGNALE_H
#define ERTOOL_ALGOCCSIGNALE_H

#include "Algo/AlgoSingleE.h"
#include "Base/AlgoBase.h"

namespace ertool {

  /**
     \class AlgoCCSignalE
     User custom SPAFilter class made by davidkaleko
   */
  class AlgoCCSignalE : public AlgoBase {
  
  public:

    /// Default constructor
    AlgoCCSignalE();

    /// Default destructor
    virtual ~AlgoCCSignalE(){};

    /// Reset function
    virtual void Reset();

    /// What to do before event-loop begins
    virtual void ProcessBegin();

    /// What to do once event-loop is over
    virtual void ProcessEnd(TFile* fout);

    /// Override the sptool::SPTBase::LoadParams function
    virtual void LoadParams(std::string fname="",size_t version=kINVALID_SIZE);

    /// Function to evaluate input showers and determine a score
    virtual ParticleSet Reconstruct(const EventData &data);

  protected:
    
    AlgoSingleE _alg_singleE;

  };
}
#endif

//**************************************************************************
// 
// For Analysis framework documentation, read Manual.pdf here:
//
// http://microboone-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=3183
//
//**************************************************************************

/** @} */ // end of doxygen group 
