/**
 * \file SPAlgoCCSignalE.h
 *
 * \ingroup SPAlgo
 * 
 * \brief This SPAlgo takes in electrons and returns electrons that are likely
 generated by a neutrino in a CC interaction.
 * It checks things like:
 *    - The electron is not at the end of a track (IE Michels)
 *    - The electron is not radiated off of another electron shower
 *    - The electron is not radiated off of another track
 *    - etc.
 *
 * @author davidkaleko
 */

/** \addtogroup SPAlgo

    @{*/

#ifndef SELECTIONTOOL_SPALGOCCSIGNALE_H
#define SELECTIONTOOL_SPALGOCCSIGNALE_H

#include "SPAlgo/SPAlgoSingleE.h"
#include "SPTBase/SPAlgoBase.h"

namespace sptool {

  /**
     \class SPAlgoCCSignalE
     User custom SPAFilter class made by davidkaleko
   */
  class SPAlgoCCSignalE : public SPAlgoBase {
  
  public:

    /// Default constructor
    SPAlgoCCSignalE();

    /// Default destructor
    virtual ~SPAlgoCCSignalE(){};

    /// Reset function
    virtual void Reset();

    /// What to do before event-loop begins
    virtual void ProcessBegin();

    /// What to do once event-loop is over
    virtual void ProcessEnd(TFile* fout);

    /// Override the sptool::SPTBase::LoadParams function
    virtual void LoadParams(std::string fname="",size_t version=kINVALID_SIZE);

    /// Function to evaluate input showers and determine a score
    virtual SPArticleSet Reconstruct(const SPAData &data);

  protected:
    
    SPAlgoSingleE _alg_singleE;

  };
}
#endif

//**************************************************************************
// 
// For Analysis framework documentation, read Manual.pdf here:
//
// http://microboone-docdb.fnal.gov:8080/cgi-bin/ShowDocument?docid=3183
//
//**************************************************************************

/** @} */ // end of doxygen group 
